/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SelfLoading: typeof import('./src/components/self-loading/self-loading.vue')['default']
    SelfNavbar: typeof import('./src/components/self-navbar/self-navbar.vue')['default']
    SelfOverlay: typeof import('./src/components/self-overlay/self-overlay.vue')['default']
    SelfSegmented: typeof import('./src/components/self-segmented/self-segmented.vue')['default']
    SelfSlider: typeof import('./src/components/self-slider/self-slider.vue')['default']
    SelfTabbar: typeof import('./src/components/self-tabbar/self-tabbar.vue')['default']
    SelfVirtuallist: typeof import('./src/components/self-virtuallist/self-virtuallist.vue')['default']
    SelfVirtuallist2: typeof import('./src/components/self-virtuallist2/self-virtuallist2.vue')['default']
  }
}
